name: CI Backend
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: poetry install --no-interaction --no-ansi
      - name: Lint
        run: poetry run flake8
      - name: Test
        run: poetry run pytest --maxfail=1 --disable-warnings -q
      - name: Build image
        run: docker build -t siriustools-backend .